a = int(input('Digite um número: '))
print('Sua tabuada é: ')
print('1 * {}'.format(a*1))
print('2 * {}'.format(a*2))
print('3 * {}'.format(a*3))
print('4 * {}'.format(a*4))
print('5 * {}'.format(a*5))
print('6 * {}'.format(a*6))
print('7 * {}'.format(a*7))
print('8 * {}'.format(a*8))
print('9 * {}'.format(a*9))
print('10 * {}'.format(a*10))
